### ISSUE TITLE
Building sigrok?

### ISSUE THREAD

**Issue by nmaas87** [abhishek-kakkar/BeagleLogic#3]
Hi, I got some problem with building sigrok. 
Description of what I did, on an Ubuntu 12.04 LTS System:

# Install add-apt-repository
sudo apt-get install python-software-properties
# Add repositorys
sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"
# Update package lists
sudo apt-get update
# Get Sigrok and Build Dependencies
 sudo apt-get install gcc-arm-linux-gnueabihf autotools-dev \
  git-core gcc g++ make autoconf autoconf-archive \
  automake libtool pkg-config libglib2.0-dev libglibmm-2.4-dev libzip-dev \
  libusb-1.0-0-dev libftdi-dev check doxygen \
  python-dev python-gi-dev python-setuptools swig default-jdk \
  python3-dev

# Get BeagleLogic
cd ~
git clone https://github.com/abhishek-kakkar/BeagleLogic/

# Get Arm Dependencies
cd ~/BeagleLogic/
wget https://d8a0b5d606f320db2dca525de17833da935fbbb0.googledrive.com/host/0B7U2bJEjkNeZSVVBMFU4WVBkS2c/sigrok-arm-libraries.tar.gz
tar -xvzf sigrok-arm-libraries.tar.gz

# Get Sigrok
cd ~/BeagleLogic/
git clone git://sigrok.org/libserialport
git clone git://sigrok.org/libsigrok
git clone git://sigrok.org/libsigrokdecode
git clone git://sigrok.org/sigrok-cli

# Build sigrok
cd ~/BeagleLogic/
sudo ./sigrok-build-beaglebone

After I start building, I get following erroR:

  CC     src/hardware/tondaj-sl-814/protocol.lo
  CC     src/hardware/tondaj-sl-814/api.lo
  CC     src/hardware/yokogawa-dlm/protocol.lo
  CC     src/hardware/yokogawa-dlm/protocol_wrappers.lo
  CC     src/hardware/yokogawa-dlm/api.lo
  CCLD   libsigrok.la
libtool: link: warning: library `/home/pi/BeagleLogic/usr/lib/libserialport.la' was moved.
/usr/lib/gcc/arm-linux-gnueabihf/4.6/../../../../arm-linux-gnueabihf/bin/ld: /home/pi/BeagleLogic/usr/lib/arm-linux-gnueabihf/libglib-2.0.a(gbytes.o): relocation R_ARM_THM_MOVW_ABS_NC against `g_free' can not be used when making a shared object; recompile with -fPIC
/home/pi/BeagleLogic/usr/lib/arm-linux-gnueabihf/libglib-2.0.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
make[1]: *** [libsigrok.la] Error 1
make: *** [all] Error 2

Any idea how to fix that?

Thanks

**Comment by abhishek-kakkar** [comment]
It's been a long time since I replied here. For all those monitoring this issue, I'll be testing BeagleLogic on Debian Jessie soon. Since it has updated version of the core libraries so once I am able to package and move everything, you can compile the latest version of libsigrok on the BeagleBone Black, and then I can close this long standing issue.

Also, I plan to get a "BeagleLogic edition" Debian Jessie system image released soon, so you can run BeagleLogic out-of-the box by flashing the image onto the eMMC/SD Card.

**Comment by abhishek-kakkar** [comment]
The newer version of sigrok libraries compile fine on the Debian Jessie on the BeagleBone Black, this issue is fixed as they have the latest libraries now.

I've also released the BeagleLogic System Image, which can be flashed to a microSD card and used to run BeagleLogic. Download and read more about it [here](https://github.com/abhishek-kakkar/BeagleLogic/wiki/BeagleLogic-Image-Guide-:-New)

This issue is now closed.
