### ISSUE TITLE
Add PulseView to image

### ISSUE THREAD

**Issue by buzmeg** [abhishek-kakkar/BeagleLogic#30]
PulseView is pretty difficult to build since it needs so much cross-compilation expertise and the dependency chain through sigrok is quite long.

Please add an image of PulseView to the BeagleLogic image on the next build.

Thanks.

**Comment by abhishek-kakkar** [comment]
In the background I have added a TCP/IP backend to BeagleLogic, so that one can use BeagleLogic with PulseView runnning on the desktop and connecting to the hardware (BeagleBone or the BeagleLogic Standalone board) via TCP/IP. So one does not, in theory, need to run PulseView on the same hardware running BeagleLogic. I have to add instructions on how to use this.

**Comment by buzmeg** [comment]
Project dead.  Closing.
