### ISSUE TITLE
System image link is broken

### ISSUE THREAD

**Issue by xouillet** [abhishek-kakkar/BeagleLogic#48]
Hi,

According to the documentation site and the github wiki [here](https://github.com/abhishek-kakkar/BeagleLogic/wiki/BeagleLogic-%22no-setup-required%22-setup:-Introducing-System-Image!), we should be able to download the system image at https://goo.gl/RiXGBs but this link sends me to a 403 error.

**Comment by mminnella** [comment]
Same issue, is it available in some other mirrors?

**Comment by abhishek-kakkar** [comment]
This issue is because of Google Drive enforcing resource keys on widely shared files. The system images are currently hosted there.

Please use this [updated link](https://drive.google.com/file/d/0ByqRLxWwTOOkSmptSkNqVXBLVm8/view?usp=sharing&resourcekey=0-ZNcpY1XLfVit0cmIbM2-Mw) which has the added resource key string to download.

**Comment by abhishek-kakkar** [comment]
Wiki link updated, closing issue.
